forge 'https://forge.puppet.com'

# NOTE: This is the control repo Puppetfile (for agent configuration)
# For Bolt modules, see igor/Puppetfile

# Core Puppet modules
mod 'puppetlabs/stdlib', '9.7.0'
mod 'puppetlabs/concat', '9.1.0'
mod 'puppetlabs/inifile', '6.2.0'
mod 'puppetlabs/apt', '9.4.0'
mod 'puppetlabs/puppet_agent', '4.21.0'
mod 'puppetlabs/node_manager', '1.1.0'
mod 'puppetlabs/yumrepo_core', '2.1.0'
mod 'puppetlabs/powershell', '6.0.2'
mod 'puppetlabs/reboot', '5.1.0'
mod 'puppetlabs/pwshlib', '1.2.3'
mod 'puppetlabs/exec', '3.1.0'

# Infrastructure modules
mod 'puppetlabs/docker', '9.1.0'
mod 'puppet/nginx', '7.0.0'
mod 'puppet/systemd', '8.2.0'
mod 'puppet/firewalld', '5.0.0'
mod 'puppet/archive', '7.1.0'
mod 'puppet/python', '8.0.0'

# Monitoring and dashboards
mod 'puppet/grafana', '14.1.0'
mod 'puppet/telegraf', '5.4.0'
mod 'puppetlabs/influxdb', '2.4.0'
mod 'puppet/prometheus', '16.4.0'
mod 'puppetlabs/puppet_operational_dashboards', '2.4.0'

# Security and compliance
mod 'puppetlabs/sce_linux', '2.5.0'
mod 'puppetlabs/nessus_transformer', '1.0.2'
mod 'puppetlabs/node_encrypt', '3.1.0'
